In [1]:
import numpy as np
import pandas as pd

In [67]:
df = pd.read_csv('/Users/ziyuanhan/Desktop/mmm_data/week5/MMM_AF_S11.csv')
df.head(3)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Period                       208 non-null    object
 1   Month                        208 non-null    object
 2   CCI                          208 non-null    int64
 3   National TV GRPs             208 non-null    int64
 4   Magazine GRPs                208 non-null    int64
 5   Paid Search                  208 non-null    int64
 6   Display                      208 non-null    int64
 7   Facebook Impressions         208 non-null    int64
 8   Wechat                       208 non-null    int64
 9   Sales Event                  208 non-null    int64
 10  Black Friday                 208 non-null    int64
 11  July 4th                     208 non-null    int64
 12  Comp Media Spend             208 non-null    int64
 13  Sales                        208 non-null    int64
 14  DisplayAlwaysOnImpression    208 non-null    int64
 15  DisplayBrandingImpression    208 non-null    int64
 16  DisplayWebsiteImpression     208 non-null    int64
 17  DisplayHolidayImpression     208 non-null    int64
 18  SearchBrandingclicks         208 non-null    int64
 19  SearchAlwasyOnclicks         208 non-null    int64
 20  SearchWebsiteclicks          208 non-null    int64
 21  FacebookBrandingImpressions  208 non-null    int64
 22  FacebookHolidayImpressions   208 non-null    int64
 23  FacebookOtherImpressions     208 non-null    int64
dtypes: int64(22), object(2)
memory usage: 39.1+ KB

In [5]:
df_selected = df[['National TV GRPs', 'Magazine GRPs', 'Paid Search', 'Display', 'Facebook Impressions', 'Wechat']]

,National TV GRPs,Magazine GRPs,Paid Search,Display,Facebook Impressions,Wechat
0,82,15,322562,36699907,10912086,451
1,72,15,287279,37155907,10231860,462
2,82,15,298089,41136934,9519178,558
3,80,20,393145,39993325,3705699,507
4,62,20,407856,41066571,9695603,609
...,...,...,...,...,...,...
203,52,20,303303,38408351,6884386,3960
204,73,20,270781,34923918,14128685,2988
205,68,20,269663,34013004,60130790,3096
206,59,20,392770,36295419,84172550,3564
207,73,20,311237,39796196,32429357,1323

In [13]:
parameters

        channel index transformation_type constant
0            tv     1                 lag        0
1            tv     2                 lag        1
2      magazine     1                 lag        1
3      magazine     2                 lag        1
4   paid_search     1                 lag        0
5   paid_search     2                 lag        1
6       display     1                 lag        0
7       display     2                 lag        0
8      facebook     1                 lag        0
9      facebook     2                 lag        1
10       wechat     1                 lag        0
11       wechat     2                 lag        1
12           tv     1               decay      0.8
13           tv     2               decay      0.8
14     magazine     1               decay      0.7
15     magazine     2               decay      0.7
16  paid_search     1               decay      0.9
17  paid_search     2               decay      0.9
18      display     1               decay      0.8
19      display     2               decay        1
20     facebook     1               decay        1
21     facebook     2               decay        1
22       wechat     1               decay      0.8
23       wechat     2               decay      0.9
24           tv     1                 pow      0.9
25           tv     2                 pow      0.6
26     magazine     1                 pow      0.6
27     magazine     2                 pow      0.9
28  paid_search     1                 pow        1
29  paid_search     2                 pow      0.7
30      display     1                 pow      0.8
31      display     2                 pow        1
32     facebook     1                 pow      0.8
33     facebook     2                 pow        1
34       wechat     1                 pow      0.9
35       wechat     2                 pow        1

In [12]:
parameters = pd.DataFrame(columns = ['channel', 'index', 'transformation_type', 'constant']) 

parameters = parameters.append({'channel': 'tv', 'index':1, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'tv', 'index':2, 'transformation_type':'lag', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':1, 'transformation_type':'lag', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':2, 'transformation_type':'lag', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':1, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':2, 'transformation_type':'lag', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':1, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':2, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':1, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':2, 'transformation_type':'lag', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':1, 'transformation_type':'lag', 'constant':0}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':2, 'transformation_type':'lag', 'constant':1}, ignore_index=True)

parameters = parameters.append({'channel': 'tv', 'index':1, 'transformation_type':'decay', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'tv', 'index':2, 'transformation_type':'decay', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':1, 'transformation_type':'decay', 'constant':.7}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':2, 'transformation_type':'decay', 'constant':.7}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':1, 'transformation_type':'decay', 'constant':.9}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':2, 'transformation_type':'decay', 'constant':.9}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':1, 'transformation_type':'decay', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':2, 'transformation_type':'decay', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':1, 'transformation_type':'decay', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':2, 'transformation_type':'decay', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':1, 'transformation_type':'decay', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':2, 'transformation_type':'decay', 'constant':.9}, ignore_index=True)

parameters = parameters.append({'channel': 'tv', 'index':1, 'transformation_type':'pow', 'constant':.9}, ignore_index=True)
parameters = parameters.append({'channel': 'tv', 'index':2, 'transformation_type':'pow', 'constant':.6}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':1, 'transformation_type':'pow', 'constant':.6}, ignore_index=True)
parameters = parameters.append({'channel': 'magazine', 'index':2, 'transformation_type':'pow', 'constant':.9}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':1, 'transformation_type':'pow', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'paid_search', 'index':2, 'transformation_type':'pow', 'constant':.7}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':1, 'transformation_type':'pow', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'display', 'index':2, 'transformation_type':'pow', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':1, 'transformation_type':'pow', 'constant':.8}, ignore_index=True)
parameters = parameters.append({'channel': 'facebook', 'index':2, 'transformation_type':'pow', 'constant':1}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':1, 'transformation_type':'pow', 'constant':.9}, ignore_index=True)
parameters = parameters.append({'channel': 'wechat', 'index':2, 'transformation_type':'pow', 'constant':1}, ignore_index=True)

In [15]:
df[['National TV GRPs']]

     National TV GRPs
0                  82
1                  72
2                  82
3                  80
4                  62
..                ...
203                52
204                73
205                68
206                59
207                73

[208 rows x 1 columns]

In [61]:
def transformation(dataframe, transformation_type, index, constant, column_name):
    ## ============== function explanation ==============
    ## This function performs lag, power and decay transformation
    ## ============== function parameter explanation ==============
    ## dataframe: input dataframe
    ## transformation.type: lag, decay or power
    ## transformation.type.index: index of transforamtion. i.e. lag1, lag2, decay1, decay2
    ## transformation.constant: the parameter used for transformation
    ## column.name: dataframe column needed for transformation
    
    if transformation_type.lower()=='lag':
        dataframe[['-'.join([column_name,transformation_type,str(index)])]] = dataframe[[column_name]].shift(periods=constant, fill_value=0)
        return
    elif transformation_type.lower()=='decay':
        new_col_name = '-'.join([column_name,transformation_type,str(index)])
        df.loc[0, new_col_name] = df.loc[0, column_name] * constant
        for i in range(1, len(df)):
            df.loc[i, new_col_name] = df.loc[i, column_name] * constant + df.loc[i-1, new_col_name] * (1-constant)
        return
    elif transformation_type.lower()=='pow':
        dataframe[['-'.join([column_name,transformation_type,str(index)])]] = dataframe[[column_name]].apply(lambda x: x**constant)
        return
    else:
        print('Only support lag, decay and power')
        return

In [62]:
transformation(df, 'lag', 1, 1, 'National TV GRPs')
transformation(df, 'pow', 1, .8, 'National TV GRPs-lag-1')
transformation(df, 'decay', 1, .4, 'National TV GRPs-lag-1-pow-1')

In [64]:
df[['National TV GRPs-lag-1-pow-1-decay-1']]

     National TV GRPs-lag-1-pow-1-decay-1
0                                0.000000
1                               13.586609
2                               20.396041
3                               25.824233
4                               28.815391
..                                    ...
203                             23.939220
204                             23.801156
205                             26.660626
206                             27.693177
207                             27.056894

[208 rows x 1 columns]

In [66]:
def transformation_sequence(dataframe, transformation_types, indexs, constants, column_name):
    ## ============== function explanation ==============
    ## This function performs a sequence of lag, power and decay transformation using transform
    ## ============== function parameter explanation ==============
    ## dataframe: input dataframe
    ## sequence: sequence of trasnformation
    ## sequence.indices: index number of the transformation
    ## values: value of transformation action
    ## column.name: name of column transformation operates on
    if len(transformation_types) != len(indexs) or len(indexs) != len(constants):
        print('not equal length')
        return
    for i in range(len(indexs)):
        transformation(dataframe, transformation_types[i], indexs[i], constants[i], column_name)
        column_name = '-'.join([column_name,transformation_types[i],str(indexs[i])])
        
    return

In [68]:
transformation_sequence(df, ['lag','pow','decay'], [1,1,1], [1,.8,.4], 'National TV GRPs')

In [69]:
df[['National TV GRPs-lag-1-pow-1-decay-1']]

     National TV GRPs-lag-1-pow-1-decay-1
0                                0.000000
1                               13.586609
2                               20.396041
3                               25.824233
4                               28.815391
..                                    ...
203                             23.939220
204                             23.801156
205                             26.660626
206                             27.693177
207                             27.056894

[208 rows x 1 columns]